language: go
sudo: false

go:
  - 1.5.x
  - 1.6.x
  - 1.7.x

install:
  - export GO15VENDOREXPERIMENT=1
  - go get github.com/Masterminds/glide
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/go-playground/overalls
  - go get github.com/mattn/goveralls
  - glide install

script:
  - go test $($GOPATH/bin/glide novendor) -cover
  - $GOPATH/bin/overalls -project=github.com/chielkunkels/marvin -covermode=count -ignore=.git,vendor

after_success:
  - $GOPATH/bin/goveralls -coverprofile=overalls.coverprofile -service=travis-ci
